apiVersion: v1
kind: Service
metadata:
    name: external
    labels:
        run: external 
spec:
    ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
      name: http
    selector:
        run: external
    type: LoadBalancer 
