
spring:
  application:
    name: external
  profiles:
    active: default
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
server:
  port: 8099

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
  
logging:
  level:
    root: debug
    org.hibernate.SQL: debug